### ISSUE TITLE
ability to limit RAM usage - feature - priority 4/10

### ISSUE THREAD

**Issue by ok236449** [AVMG20/smart-support-bot#4]
It would be very useful if it was possible for the bot to know its limits. If it runs in pterodactyl as a half GB server, if someone posts a big image, it exceeds the limit, and ptero is of course going to kill it as a process. If it knew its limits (maybe thru config) it would be aware of it and maybe could manage its usage accordingly.

I know it is a lot of work, but it could be worth it.

**Comment by AVMG20** [comment]
hey hey, sorry for responding this late. you can set a limit in pterodactyl on how much ram it can use. if you don't allow to big of an image, it should be fine :) haven't had any issues on controlpanel
