### ISSUE TITLE
[IDEA]: user whilelist with a bypass prefix

### ISSUE THREAD

**Issue by Bricklou** [AVMG20/smart-support-bot#6]
Be able to whilelist some specific user to be read from the bot and check anyway if the user add a prefix at the beginning of the message.

**Comment by AVMG20** [comment]
What?

**Comment by Bricklou** [comment]
Maybe I didn't explained well
It would be interesting to be able to add some users to a whitelist (blacklist would technically be a better term)
if the user is in the list, the bot will not respond if a message pattern is detected
but he still can force the bot to send the message by adding a prefix at the beginning of the messag

I don't know if it is clearer or not.

**Comment by 1day2die** [comment]
That's a helpful idea. We could blacklist all supoirt members from bot responses

**Comment by ShadowHub-Nodes** [comment]
bots broken.. only 1 response works.. image doesnt work either.. triued addin you but no response from dickheads like you
